name: "Setup SAOG Action"
description: "A GitHub Action to set up SAOG environment."
inputs:
  exampleInput:
    description: "An example input for the action."
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  entrypoint: "entrypoint.sh"
